language: node_js
node_js:
  - "lts/*"
cache: yarn
# The lines below should fix the travis build according to this issue (https://github.com/kelektiv/node.bcrypt.js/issues/366)
env:
  global:
    - secure: "jMY/v3C4pXIAPETth0/MGTXJ8Xc6ygaS1P+/ekjPfL4rdzu+Ny/ZopOfBoamDxHHJywxwvlwADKb/uI4wV2koOM5KGfOnfy8YtTF8Pj3yxeXsRzSnNk8yqOJhbqQD5Wreh10l8+kjlNdql+bL25QxJ0FJl6TAjcZgsb0M83/Mt+8vh0LwpIksMxHrpNJo23+koLaQy9PHv3gKQ3GK0K1Ob51dAh6MZVMshV7YfE2+z5fLMN+JvO5gGUGcqQmodMGZgu6f2YAxAENC/phf7kjGE6bNMMqYr1TZSj7VIdHkoThmkWCRph9JQiGoSI4oRkwrEu3Lsd0BtOtmxHpqfbJrQuh0oqWSmyw9WvxyP8u7/b6usWesGgVdB3O0IfbqVP+/K/7Clcit1v8c0Q1dVjjD9u87NMZiYnbl6cE/HFVfeGIfFEbThLKzIC97VjdrMwxdsaYsp+h9FRzlfW5U1gCoBH+tywbmdmHvq38HL1PYWGPhJw6FNzkXuUQLoeK1d6mntZWevR46VGtLUZ5H8OLtjoAq+9z1d9n1mQcaYWbj4guhxue9WM8StWNbxs3r9+rzf4AGVG4rycSrlyNkVC3/iD0f7SMuhFxv1cVsf9VTpNyfZ/0qISGg1XsX4G6KQvwwe8QylFmH7o1ylnZwUNb575F8/DQY0dC5YNt4oFplUY="
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  - provider: script
    script: yarn now --token $NOW_ACCESS_TOKEN && yarn now alias --token $NOW_ACCESS_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: script # required env variables NETLIFY_AUTH_TOKEN
    script: cd client && yarn && yarn build && yarn netlify deploy --dir client/build --prod
    skip_cleanup: true
    on:
      branch: master
