FROM node:8.11.4
MAINTAINER kino1134

WORKDIR /opt
# キャッシュ回避
ADD package.json /data/
RUN git clone https://github.com/kino1134/chatta_react.git \
  && cd chatta_react/client \
  && yarn install \
  && yarn build

FROM nginx:1.15.3
COPY --from=0 /opt/chatta_react/client/build /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
