version: "2.2"

services:
  # web:
  #   build: .
  #   init: true
  #   ports:
  #     - "80:3000"
  #   volumes:
  #     - "$PWD:/opt/module" # 「.」だけだとダメなので$PWDを使用
  #     - "/opt/module/node_modules" # コンテナのモジュールを使用
  #   environment:
  #     WEB_HOST: 0.0.0.0
  #     MONGO_HOST: mongodb
  #     REDIS_HOST: redis
  #   depends_on:
  #     - mongodb
  #     - redis
  mongodb:
    image: mongo:3.6.3
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo/db:/data/db"
      - "./data/mongo/config:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass1!
  redis:
    image: redis:4.0.9
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis/db:/data"
